# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pose_tracking.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(_runtime_version.Domain.PUBLIC, 7, 35, 1, "", "pose_tracking.proto")
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13pose_tracking.proto\x12\x04r2st"F\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x04 \x01(\x05"\xfd\x01\n\x0fRegisterRequest\x12\x11\n\tmesh_path\x18\x01 \x01(\t\x12\x1e\n\tcolor_rgb\x18\x02 \x01(\x0b\x32\x0b.r2st.Image\x12\x1c\n\x07\x64\x65pth_m\x18\x03 \x01(\x0b\x32\x0b.r2st.Image\x12\x19\n\x04mask\x18\x04 \x01(\x0b\x32\x0b.r2st.Image\x12\x10\n\x08k_matrix\x18\x05 \x03(\x02\x12\x11\n\titeration\x18\x06 \x01(\x05\x12\x16\n\x0euse_2d_tracker\x18\x07 \x01(\x08\x12\x19\n\x11use_kalman_filter\x18\x08 \x01(\x08\x12&\n\x1ekalman_measurement_noise_scale\x18\t \x01(\x02"q\n\x0cTrackRequest\x12\x1e\n\tcolor_rgb\x18\x01 \x01(\x0b\x32\x0b.r2st.Image\x12\x1c\n\x07\x64\x65pth_m\x18\x02 \x01(\x0b\x32\x0b.r2st.Image\x12\x10\n\x08k_matrix\x18\x03 \x03(\x02\x12\x11\n\titeration\x18\x04 \x01(\x05" \n\x0cPoseResponse\x12\x10\n\x08pose_cam\x18\x01 \x03(\x02\x32v\n\x0cPoseTracking\x12\x35\n\x08Register\x12\x15.r2st.RegisterRequest\x1a\x12.r2st.PoseResponse\x12/\n\x05Track\x12\x12.r2st.TrackRequest\x1a\x12.r2st.PoseResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pose_tracking_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_IMAGE"]._serialized_start = 29
    _globals["_IMAGE"]._serialized_end = 99
    _globals["_REGISTERREQUEST"]._serialized_start = 102
    _globals["_REGISTERREQUEST"]._serialized_end = 355
    _globals["_TRACKREQUEST"]._serialized_start = 357
    _globals["_TRACKREQUEST"]._serialized_end = 470
    _globals["_POSERESPONSE"]._serialized_start = 472
    _globals["_POSERESPONSE"]._serialized_end = 504
    _globals["_POSETRACKING"]._serialized_start = 506
    _globals["_POSETRACKING"]._serialized_end = 624
# @@protoc_insertion_point(module_scope)
