# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
#
# Regenerate with (from src/r2st/pose_grpc/):
#   uv run python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. pose_tracking.proto
# then re-apply the `from r2st.pose_grpc import ...` fix to the `pose_tracking_pb2` import below
# (protoc emits a bare top-level import, which breaks once this file is imported as a package).
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from r2st.pose_grpc import pose_tracking_pb2 as pose__tracking__pb2

GRPC_GENERATED_VERSION = "1.83.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in pose_tracking_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class PoseTrackingStub:
    """Runs FoundationPose object pose estimation/tracking inside the FoundationPose Docker
    container (see src/r2st/FoundationPose/docker). The server holds a single active tracked
    object at a time: `Register` (re)initializes the tracked object from its first frame, and
    subsequent `Track` calls refine that pose frame-to-frame until the next `Register` call
    replaces it. Mirrors the r2st.pose_tracking.FoundationPoseTracker API.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
            "/r2st.PoseTracking/Register",
            request_serializer=pose__tracking__pb2.RegisterRequest.SerializeToString,
            response_deserializer=pose__tracking__pb2.PoseResponse.FromString,
            _registered_method=True,
        )
        self.Track = channel.unary_unary(
            "/r2st.PoseTracking/Track",
            request_serializer=pose__tracking__pb2.TrackRequest.SerializeToString,
            response_deserializer=pose__tracking__pb2.PoseResponse.FromString,
            _registered_method=True,
        )


class PoseTrackingServicer:
    """Runs FoundationPose object pose estimation/tracking inside the FoundationPose Docker
    container (see src/r2st/FoundationPose/docker). The server holds a single active tracked
    object at a time: `Register` (re)initializes the tracked object from its first frame, and
    subsequent `Track` calls refine that pose frame-to-frame until the next `Register` call
    replaces it. Mirrors the r2st.pose_tracking.FoundationPoseTracker API.
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Track(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_PoseTrackingServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Register": grpc.unary_unary_rpc_method_handler(
            servicer.Register,
            request_deserializer=pose__tracking__pb2.RegisterRequest.FromString,
            response_serializer=pose__tracking__pb2.PoseResponse.SerializeToString,
        ),
        "Track": grpc.unary_unary_rpc_method_handler(
            servicer.Track,
            request_deserializer=pose__tracking__pb2.TrackRequest.FromString,
            response_serializer=pose__tracking__pb2.PoseResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("r2st.PoseTracking", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("r2st.PoseTracking", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class PoseTracking:
    """Runs FoundationPose object pose estimation/tracking inside the FoundationPose Docker
    container (see src/r2st/FoundationPose/docker). The server holds a single active tracked
    object at a time: `Register` (re)initializes the tracked object from its first frame, and
    subsequent `Track` calls refine that pose frame-to-frame until the next `Register` call
    replaces it. Mirrors the r2st.pose_tracking.FoundationPoseTracker API.
    """

    @staticmethod
    def Register(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/r2st.PoseTracking/Register",
            pose__tracking__pb2.RegisterRequest.SerializeToString,
            pose__tracking__pb2.PoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Track(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/r2st.PoseTracking/Track",
            pose__tracking__pb2.TrackRequest.SerializeToString,
            pose__tracking__pb2.PoseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
